name: pipeline-break

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: pipeline-break-job
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: breakingpipeline
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
