name: pipeline-break

on: 
  workflow_dispatch:
    inputs:
          command:
            required: true
            default: 'make-error'
jobs:
  build:
    name: pipeline-break-job
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: ${{github.event.inputs.command}} "Hello world" 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
